title: My Personal Blog
description: Course assignment website for command line, Markdown, Python, Git, and GitHub Pages

theme: jekyll-theme-cayman

markdown: kramdown

url: "https://wuyuekai666.github.io"
baseurl: "/personal-blog"